# Generated by Django 5.2.16 on 2026-07-08 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityWorkingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('general', 'Общий режим работы'), ('instructor', 'С инструктором'), ('break', 'Перерыв')], default='general', max_length=20, verbose_name='Тип')),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], help_text='Пусто — ежедневно', null=True, verbose_name='День недели')),
                ('time_start', models.TimeField(verbose_name='Начало')),
                ('time_end', models.TimeField(verbose_name='Окончание')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_schedules', to='schools.facility', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'График работы объекта',
                'verbose_name_plural': 'Графики работы объектов',
                'ordering': ['facility', 'schedule_type', 'weekday', 'time_start'],
            },
        ),
        migrations.CreateModel(
            name='SchedulePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('date_from', models.DateField(verbose_name='Дата начала')),
                ('date_to', models.DateField(verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущий период')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_periods', to='schools.facility', verbose_name='Объект')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_periods', to='schools.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Период расписания',
                'verbose_name_plural': 'Периоды расписания',
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('time_start', models.TimeField(verbose_name='Начало')),
                ('time_end', models.TimeField(verbose_name='Окончание')),
                ('age_group', models.CharField(blank=True, max_length=100, verbose_name='Возрастная группа')),
                ('group_name', models.CharField(blank=True, max_length=255, verbose_name='Группа')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='schools.coach', verbose_name='Тренер')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='schools.facility', verbose_name='Объект')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='schools.school', verbose_name='Школа')),
                ('sport_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='schools.sportdirection', verbose_name='Направление')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='schedules.scheduleperiod', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Занятие в расписании',
                'verbose_name_plural': 'Расписание занятий',
                'ordering': ['weekday', 'time_start'],
            },
        ),
        migrations.CreateModel(
            name='PoolSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('time_start', models.TimeField(verbose_name='Начало')),
                ('time_end', models.TimeField(verbose_name='Окончание')),
                ('session_type', models.CharField(blank=True, help_text='Например: детский, взрослый, свободное плавание', max_length=100, verbose_name='Тип сеанса')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_sessions', to='schools.facility', verbose_name='Объект')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_sessions', to='schedules.scheduleperiod', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Сеанс бассейна',
                'verbose_name_plural': 'Сеансы бассейна',
                'ordering': ['weekday', 'time_start'],
            },
        ),
    ]
