# Generated by Django 5.2.16 on 2026-07-08 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-имя')),
                ('facility_type', models.CharField(choices=[('pool', 'Бассейн'), ('gym', 'Тренажёрный зал'), ('game_hall', 'Игровой зал'), ('combat_hall', 'Зал единоборств'), ('tennis', 'Теннисные корты'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип объекта')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('phone_admin', models.CharField(blank=True, max_length=100, verbose_name='Телефон администрации')),
                ('working_hours', models.CharField(blank=True, max_length=255, verbose_name='Режим работы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('has_hall_rental', models.BooleanField(default=False, verbose_name='Аренда зала')),
                ('hall_rental_note', models.TextField(blank=True, verbose_name='Примечание по аренде')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('photo', models.ImageField(blank=True, upload_to='facilities/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Спортивный объект',
                'verbose_name_plural': 'Спортивные объекты',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-имя')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('opened_date', models.DateField(blank=True, null=True, verbose_name='Дата открытия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Спортивная школа',
                'verbose_name_plural': 'Спортивные школы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование услуги')),
                ('price', models.CharField(max_length=100, verbose_name='Стоимость')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_items', to='schools.facility', verbose_name='Объект')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='schools.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Позиция прейскуранта',
                'verbose_name_plural': 'Прейскурант',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='schools.school', verbose_name='Школа'),
        ),
        migrations.CreateModel(
            name='SportDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='URL-имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('age_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст от')),
                ('age_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст до')),
                ('level', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('all', 'Любой уровень')], default='all', max_length=20, verbose_name='Уровень подготовки')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('photo', models.ImageField(blank=True, upload_to='sports/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_directions', to='schools.facility', verbose_name='Объект')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_directions', to='schools.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Направление подготовки',
                'verbose_name_plural': 'Направления подготовки',
                'ordering': ['order', 'name'],
                'unique_together': {('school', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('photo', models.ImageField(blank=True, upload_to='coaches/', verbose_name='Фото')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('qualification', models.TextField(blank=True, verbose_name='Квалификация')),
                ('sports_titles', models.TextField(blank=True, verbose_name='Спортивные звания')),
                ('experience', models.TextField(blank=True, verbose_name='Опыт работы')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения воспитанников')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='schools.facility', verbose_name='Объект')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='schools.school', verbose_name='Школа')),
                ('sport_directions', models.ManyToManyField(blank=True, related_name='coaches', to='schools.sportdirection', verbose_name='Направления')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренерский состав',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
