# Generated by Django 5.2.16 on 2026-08-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='schools/', verbose_name='Фото школы'),
        ),
    ]
