# Generated by Django 5.2.16 on 2026-07-08 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('doc_type', models.CharField(choices=[('license', 'Лицензия / сертификат'), ('charter', 'Устав'), ('personal_data', 'Положение о персональных данных'), ('consent', 'Согласие на обработку данных'), ('privacy', 'Политика конфиденциальности'), ('admission', 'Правила приёма'), ('achievement', 'Достижения'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип')),
                ('file', models.FileField(blank=True, upload_to='documents/', verbose_name='Файл')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-имя')),
                ('body', models.TextField(verbose_name='Текст')),
                ('category', models.CharField(choices=[('competition', 'Соревнования'), ('victory', 'Победы'), ('recruitment', 'Набор в группы'), ('event', 'Мероприятия'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Фото')),
                ('video_url', models.URLField(blank=True, verbose_name='Видео (URL)')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('equipment', 'Что взять на тренировку'), ('medical', 'Медицинские справки'), ('rules', 'Правила посещения'), ('safety', 'Техника безопасности'), ('faq', 'Частые вопросы'), ('gto', 'ГТО'), ('pool_rules', 'Правила бассейна')], max_length=20, unique=True, verbose_name='Раздел')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Информация для родителей',
                'verbose_name_plural': 'Родителям',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Спортивные школы Елабуги', max_length=255, verbose_name='Название сайта')),
                ('hero_title', models.CharField(blank=True, max_length=500, verbose_name='Заголовок на главной')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Подзаголовок на главной')),
                ('hero_image', models.ImageField(blank=True, upload_to='site/', verbose_name='Баннер главной')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('vk_url', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('price_list_file', models.FileField(blank=True, upload_to='documents/', verbose_name='Файл прейскуранта (аренда)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='CompetitionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_date', models.DateField(verbose_name='Дата')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Место')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Календарь соревнований',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фото')),
                ('category', models.CharField(choices=[('training', 'Тренировки'), ('competition', 'Соревнования'), ('awards', 'Награждения'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
