# Generated by Django 5.2.16 on 2026-08-18 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Фото / видео галереи', 'verbose_name_plural': 'Фото и видео галереи'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на YouTube, VK или другой видеохостинг', verbose_name='Видео (URL)'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('training', 'Тренировки'), ('competition', 'Соревнования'), ('awards', 'Награждения'), ('video', 'Видео')], default='training', max_length=20, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery/', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-имя')),
                ('category', models.CharField(choices=[('training', 'Тренировки'), ('competition', 'Соревнования'), ('awards', 'Награждения'), ('video', 'Видео')], default='training', max_length=20, verbose_name='Раздел')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Дата мероприятия')),
                ('cover', models.ImageField(blank=True, upload_to='gallery/covers/', verbose_name='Обложка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Альбом галереи',
                'verbose_name_plural': 'Альбомы галереи',
                'ordering': ['order', '-event_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.galleryalbum', verbose_name='Альбом'),
        ),
    ]
