# Generated by Django 5.2.16 on 2026-08-19 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_gallery_albums'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryalbum',
            options={'ordering': ['order', '-event_date', '-id'], 'verbose_name': 'Мероприятие галереи', 'verbose_name_plural': 'Галерея: мероприятия'},
        ),
        migrations.AddField(
            model_name='document',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('license', 'Лицензия / сертификат'), ('charter', 'Устав'), ('personal_data', 'Положение о персональных данных'), ('consent', 'Согласие на обработку данных'), ('privacy', 'Политика конфиденциальности'), ('admission', 'Правила приёма'), ('achievement', 'Достижения'), ('price_list', 'Прейскурант'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип'),
        ),
    ]
